In [1]:
# numPy = numerical python
# # numpy is a python library used for working with arrays.
# # numpy aims to provide an array object that is upto 50X faster than traditional pythonlists.
# # the array object in numpy is called ndarray.

In [2]:
# arrays vs list

# arrays are very fast and memory efficient
# 50X faster than list
#  NumPy is the fundamental package for array computing with Python.


In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
# # pip is a package manager for python that allows you to install additonal libraries and packages
# conda install numpy

# checking version of NumPy

In [5]:
pip show numpy

Name: numpy
Version: 1.23.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\programdata\anaconda3\lib\site-packages
Requires: 
Required-by: astropy, bokeh, Bottleneck, category-encoders, contourpy, daal4py, datashader, datashape, gensim, h5py, holoviews, hvplot, imagecodecs, imageio, imbalanced-learn, matplotlib, mkl-fft, mkl-random, mlxtend, numba, numexpr, pandas, patsy, pyerfa, PyWavelets, scikit-image, scikit-learn, scipy, seaborn, statsmodels, tables, tifffile, transformers, xarray
Note: you may need to restart the kernel to use updated packages.


# for checking python version


In [6]:
# for checking python version
!python --version

Python 3.10.9


In [7]:
import numpy as np
print(np.__version__)

1.23.5


In [8]:
# pip  install -- upgrade numpy
# for upgrade the libraries

In [9]:
# dimensions in array
# 1D arrays
# 2D arrays
# 3D aarays

In [10]:
import numpy as np 
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(len(arr1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
6


# 0 - D array

In [11]:
arr2 = np.array([50])
print(arr2)

[50]


#  1- D array

In [12]:
arr3 = np.array([1,2,3,4,5])
print(arr3)

[1 2 3 4 5]


#  2- D array


In [13]:
arr4 = np.array([[1,2,3],[4,5,6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

#  3- D array


In [14]:
arr5 =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# check number of dimensions


In [15]:
import numpy as np
a = np.array(10)
b = np.array([10,20,30])
c = np.array([[10,20,30],[40,50,60]])
d= np.array([[[11,22,33],[44,55,66],[77,88,99]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)



0
1
2
3


# Pandas - panel data 

In [16]:
import pandas as pd
import numpy as np



In [17]:

data = np.array([1,2,3,4,5,6,7,8,9,0])
#print(data)

ser1 = pd.Series(data)
print(ser1)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9    0
dtype: int32


# creating a data frame

In [18]:
list1 = ["I","like", "ice-creams",2,4,"shiv",10]
df = pd.DataFrame(list1)
df

0
0           I
1        like
2  ice-creams
3           2
4           4
5        shiv
6          10

In [19]:
list2 = ["shri Ram","shri Krishna", "om namah shivay","har har mahadev"]
df = pd.DataFrame(list2)
df
 


0
0         shri Ram
1     shri Krishna
2  om namah shivay
3  har har mahadev

In [20]:
list3 = ["shubham", "ankush", "akshay","rachel"]
df = pd.DataFrame(list3)
age = [23,25,36,45]
location = ["mumbai","pune","delhi","Mp"]
df["age"]= age
df["location"] = location

# print("Before renaming  the column", df)
#  to rename the columns
df.rename(columns=  {0:"name"},inplace=True)
df.rename(columns= {"location"})
df

TypeError: 'set' object is not callable

In [ ]:
#USE read_csv for reading a file.

In [ ]:
df = pd.read_csv("drug200.csv")
#print first 5 rows
df.head()


In [ ]:
#print last 5 rows
df.tail()

In [ ]:
# print no. of coloums and rows
df.shape

In [ ]:
# print no. of coloums and rows
df.coloums

In [ ]:

import matplotlib.pyplot as plt

In [ ]:
import pandas as pd
data = {"names":["rajat","shubh","shri ram","shri krishna","shri ji","ma janki"],
        "age":[25,28,30,22,21,29],
        "qualification":["bsc","msc","bba","mba","ca","btech"]}
df = pd.DataFrame(data)
df
print(df[["names"]])
print(df[["age"]])

In [ ]:
# # iloc index location
# access single coloums 
row3  = df.iloc[2]
row3

# Working with missing data 

In [ ]:
# filling missing values
import numpy as np
import pandas as pd
data1 = {"first_score": [99,88,np.nan,94],
        "second_score":[78,97,72,np.nan],
        "third_score":[np.nan,40,50,42]}
df = pd.DataFrame(data1)
df


In [ ]:
df.isnull() #for finding null values use this code

In [ ]:
df.isnull().sum()

In [ ]:
df1 =df.fillna(df["first_score"].mean())
df1


In [ ]:
df.fillna(method="ffill",inplace=True)
df #ffill is used for fillinh front values

In [ ]:
df.fillna(method="bfill",inplace=True)  #bfill is used forfilling back  values
df


In [ ]:
import numpy as np
import pandas as pd
data1 = {"first_score": [99,88,np.nan,94],
        "second_score":[78,97,72,np.nan],
        "third_score":[np.nan,40,50,42]}
df = pd.DataFrame(data1)
df

In [ ]:
df.dropna(inplace = True) #it will show the table which has no N/A arugments
#df.dropna

In [ ]:
df.dropna()

In [ ]:
df

In [ ]:
data = {"key":[4,5,6,66,np.nan],
       "key2":[20,10,55,np.nan,64],
       "key3":[1,64,65,78,np.nan]}
df =pd.DataFrame(data)
df.dropna(axis=0,inplace=True)
df


In [ ]:
data = {"key":[4,5,6,66,np.nan],
       "key2":[20,10,55,np.nan,64],
       "key3":[1,64,65,78,np.nan]}
df =pd.DataFrame(data)
df.dropna()


In [ ]:
df.dropna(axis=0,inplace=True)
df

In [ ]:
df.isnull().sum()

In [ ]:
df3=df.fillna(df["key"].median())
df3

In [ ]:
df3=df.fillna(df["key"].mode()[0]) #mode is used for frequent used values
df3

# The Replace Method

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({'A':[10,23,np.nan,10,np.nan],
                  'B':[np.nan,np.nan,4.5,18,20],
                  'C':[np.nan,'python','c++','react','java'],
                  'D':['sound',np.nan,np.nan,'music','movies']})
df

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.describe()

In [ ]:
df.isnull().sum()  #it is used to check the total null values in dataset.

In [ ]:
#replaces null values with the mean
df["A"].replace([np.nan],df["A"].mean(),inplace= True)
df

In [ ]:
df["B"].replace([np.nan],df["A"].mean(),inplace=True)
df

In [ ]:
df = pd.DataFrame({'A':[10,23,np.nan,10,np.nan],
                  'B':[np.nan,np.nan,4.5,18,20],
                  'C':[np.nan,'python','c++','react','java'],
                  'D':['sound',np.nan,np.nan,'music','movies']})
df["C"].replace([np.nan],df["C"].mode()[0],inplace =True)
df


In [ ]:
df = pd.DataFrame({'A':[10,23,np.nan,10,np.nan],
                  'B':[np.nan,np.nan,4.5,18,20],
                  'C':[np.nan,'python','c++','react','java'],
                  'D':['sound',np.nan,np.nan,'music','movies']})
df["D"].replace([np.nan],"pandas",inplace= True)
df


In [ ]:
df["A"].replace([np.nan],"ShirRam",inplace = True)
df

# fill missing data with interpolate

In [ ]:
df = pd.DataFrame({'A':[10,23,np.nan,10,np.nan],
                  'B':[np.nan,np.nan,4.5,18,20],
                  'C':[np.nan,'python','c++','react','java'],
                  'D':['sound',np.nan,np.nan,'music','movies']})

df.interpolate(method= "linear",limit_direction="backward",inplace = True)
df